# Generated by Django 5.2.7 on 2026-07-13 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolylineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coordinates', models.JSONField()),
                ('color', models.CharField(max_length=7)),
                ('stroke_width', models.PositiveSmallIntegerField()),
                ('opacity', models.FloatField()),
                ('line_style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('dotted', 'Dotted')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polyline_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_polyline_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'polyline_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Polyline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('coordinates', models.JSONField()),
                ('color', models.CharField(max_length=7)),
                ('stroke_width', models.PositiveSmallIntegerField()),
                ('opacity', models.FloatField()),
                ('line_style', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polylines', to=settings.AUTH_USER_MODEL)),
                ('source_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='polyline', to='maps_app.polylinerequest')),
            ],
            options={
                'db_table': 'polylines',
                'ordering': ['-created_at'],
            },
        ),
    ]
