# Generated by Django 5.2.7 on 2026-07-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0002_polylinerequest_polyline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polyline',
        ),
    ]
