# Generated by Django 5.2.7 on 2026-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0003_delete_polyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='polylinerequest',
            name='published_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
