# Generated by Django 5.2.7 on 2026-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0004_polylinerequest_published_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='polylinerequest',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
