# Generated by Django 5.2.7 on 2026-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0005_polylinerequest_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='polylinerequest',
            name='delete_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='polylinerequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
