# Generated by Django 5.2.7 on 2026-07-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0006_polylinerequest_delete_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delete_roads',
            field=models.BooleanField(default=False, verbose_name='Delete Roads'),
        ),
    ]
