# Generated by Django 5.2.7 on 2026-07-20 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0007_customuser_delete_roads'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('polyline', 'Polyline'), ('polygon', 'Polygon'), ('circle', 'Circle'), ('rectangle', 'Rectangle'), ('marker', 'Marker')], db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geometry', models.JSONField()),
                ('style', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_snapshot', models.JSONField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('delete_requested', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='map_feature_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_map_feature_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'map_features',
                'ordering': ['-created_at'],
            },
        ),
    ]
