# Generated by Django 5.2.7 on 2026-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0011_simplify_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='property_permission',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='road_permission',
        ),
        migrations.AddField(
            model_name='customuser',
            name='property_delete_permission',
            field=models.BooleanField(default=False, verbose_name='Property Delete Permission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='property_edit_permission',
            field=models.BooleanField(default=False, verbose_name='Property Edit Permission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='road_delete_permission',
            field=models.BooleanField(default=False, verbose_name='Road Delete Permission'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='road_edit_permission',
            field=models.BooleanField(default=False, verbose_name='Road Edit Permission'),
        ),
        migrations.DeleteModel(
            name='PolylineRequest',
        ),
    ]
