# Generated by Django 5.2.7 on 2026-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0012_remove_customuser_property_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfeature',
            name='feature_type',
            field=models.CharField(choices=[('polyline', 'Polyline'), ('polygon', 'Polygon')], db_index=True, max_length=20),
        ),
    ]
